### ISSUE TITLE
About L&T

### ISSUE THREAD

**Issue by ChallaraoNalam** [Abiramikoperundevi/M1_Project_2022#2]
Hi , if you don't mind. I need help regrading the project bro. please contact me if you read the message.
My repo
RSVP[https://github.com/ChallaraoNalam](url)

**Comment by Abiramikoperundevi** [comment]
Tell me bro what kind of help did you need

**Comment by ChallaraoNalam** [comment]
hey if you don't mind guide me in project. I have completed my coding for the project and i need to know how to do testing documentation and makefiles and other stuff.
if you are comfortable to help me let me know 
my mail- id:18A81A0535@sves.org.in
my insta id :challaraonalam.

**Comment by Abiramikoperundevi** [comment]
Bro sorry for the late reply I have some college work to do tell me your
issues now

**Comment by ChallaraoNalam** [comment]
Hey thanks for reply, I have done my coding and how do i write the test file for the code

**Comment by ChallaraoNalam** [comment]
Hey reply if you see the message

**Comment by Abiramikoperundevi** [comment]
You just refer the stepin templete in that you got a perfect answer for that
