### ISSUE TITLE
Need Help 

### ISSUE THREAD

**Issue by Sachinrudra** [Abiramikoperundevi/M1_Project_2022#4]
Hey I really need your help on makefile and inc , src , test file 
 Please help me out 
these are last file i'm stuck on 
I hope u understand

**Comment by Abiramikoperundevi** [comment]
U just refer the stepin templete it will be very helpful for you

**Comment by Sachinrudra** [comment]
> stepin templete it will be very helpful for

I did I spent last night  over it but could  not  figure it out.
please do me a favour i know it lot to ask but can i send you my project .Can you pleaseeee make my file these file mentioned above.Otherwise I'm In Lot of Trouble .
I hope You & Thank You For Replying

**Comment by Abiramikoperundevi** [comment]
for inc and src file did u just go through my repo u got some idea about that
